version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-bookkeeper-postgres
    environment:
      POSTGRES_USER: bookkeeper
      POSTGRES_PASSWORD: bookkeeper_dev_pass
      POSTGRES_DB: aibookkeeper
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookkeeper -d aibookkeeper"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-bookkeeper-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: ai-bookkeeper-network
