services:
  # Backend API Service (FastAPI)
  - type: web
    name: ai-bookkeeper-api
    env: python
    rootDir: app
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PASSWORD_RESET_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false  # set after first web deploy, e.g. https://ai-bookkeeper-web.onrender.com
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UI_ASSESSMENT
        value: "1"
      - key: AUTOPOST_ENABLED
        value: "false"
      - key: GATING_THRESHOLD
        value: "0.90"
      - key: OCR_PROVIDER
        value: "tesseract"
      - key: LOG_LEVEL
        value: "INFO"
    
    # Run migrations automatically on deploy
    preDeployCommand: "alembic current || true"

  # Frontend Web Service (Next.js)
  - type: web
    name: ai-bookkeeper-web
    env: node
    rootDir: frontend
    buildCommand: |
      if [ -f package-lock.json ]; then npm ci; else npm install; fi
      npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_API_URL
        value: "https://ai-bookkeeper-api.onrender.com"
      - key: NEXT_PUBLIC_GA_MEASUREMENT_ID
        sync: false