services:
  - type: web
    name: ai-bookkeeper-web
    runtime: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PASSWORD_RESET_SECRET
        generateValue: true
      - key: UI_ASSESSMENT
        value: "1"
      - key: AUTOPOST_ENABLED
        value: "false"
      - key: GATING_THRESHOLD
        value: "0.90"
      - key: OCR_PROVIDER
        value: tesseract

  - type: worker
    name: ai-bookkeeper-worker
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: OCR_PROVIDER
        value: tesseract
      - key: AUTOPOST_ENABLED
        value: "false"
      - key: GATING_THRESHOLD
        value: "0.90"
