services:
  # Single Web Service (FastAPI + Next.js in Docker)
  - type: web
    name: ai-bookkeeper
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PASSWORD_RESET_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UI_ASSESSMENT
        value: "1"
      - key: AUTOPOST_ENABLED
        value: "false"
      - key: GATING_THRESHOLD
        value: "0.90"
      - key: OCR_PROVIDER
        value: "tesseract"
      - key: LOG_LEVEL
        value: "INFO"
      - key: NEXT_PUBLIC_API_URL
        value: "https://ai-bookkeeper.onrender.com"
      - key: NEXT_PUBLIC_GA_MEASUREMENT_ID
        sync: false

    # Run migrations automatically on deploy
    preDeployCommand: "alembic current || true"