services:
  # Web service (FastAPI + Gunicorn)
  - type: web
    name: ai-bookkeeper-web
    runtime: docker
    plan: free
    healthCheckPath: /healthz
    startCommand: "/app/docker-entrypoint.sh"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PASSWORD_RESET_SECRET
        generateValue: true
      - key: UI_ASSESSMENT
        value: "1"
      - key: AUTOPOST_ENABLED
        value: "false"
      - key: GATING_THRESHOLD
        value: "0.90"
      - key: OCR_PROVIDER
        value: tesseract
      - key: LOG_LEVEL
        value: "INFO"
    
    # Run migrations automatically on deploy (|| true makes it non-blocking)
    preDeployCommand: "alembic current || true"
    postDeployCommand: "alembic upgrade head"
  
  # Background Worker (RQ) - requires Starter plan or higher
  - type: worker
    name: ai-bookkeeper-worker
    runtime: docker
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: OCR_PROVIDER
        value: tesseract
      - key: AUTOPOST_ENABLED
        value: "false"
      - key: GATING_THRESHOLD
        value: "0.90"
      - key: LOG_LEVEL
        value: "INFO"
    
    startCommand: "rq worker -u $REDIS_URL ai_bookkeeper"
  
  # Daily Analytics Cron - requires Starter plan or higher
  - type: cron
    name: ai-bookkeeper-analytics-cron
    runtime: docker
    plan: starter
    schedule: "0 2 * * *"  # 02:00 UTC daily
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: LOG_LEVEL
        value: "INFO"
    
    startCommand: "python jobs/analytics_rollup.py"
