#!/usr/bin/env bash
# Demo of Google Cloud Run Migration Process
# This shows what the migration would look like with proper setup

set -euo pipefail

echo "🚀 GOOGLE CLOUD RUN MIGRATION DEMO"
echo "=================================="
echo ""
echo "This demonstrates what the migration process would look like"
echo "once you have completed the prerequisites setup."
echo ""

echo "📋 STEP 1: Environment Setup"
echo "-----------------------------"
echo "export PROJECT=\"ai-bookkeeper-prod\""
echo "export REGION=\"us-central1\""
echo "export GCP_SA_JSON_PATH=\"/path/to/service-account.json\""
echo "export WEB_ORIGINS=\"https://app.ai-bookkeeper.app,https://ai-bookkeeper-web.onrender.com\""
echo "export JWT_SECRET=\"$(openssl rand -hex 32)\""
echo "export MIGRATE_WEB=false"
echo "export DOMAIN_ROOT=\"ai-bookkeeper.app\""
echo ""

echo "📋 STEP 2: Prerequisites Check"
echo "------------------------------"
echo "bash scripts/check_prerequisites.sh"
echo ""
echo "Expected output:"
echo "✅ OS supported: darwin24"
echo "✅ bash: GNU bash, version..."
echo "✅ curl: curl 8.7.1..."
echo "✅ jq: jq-1.7.1..."
echo "✅ python3: Python 3.13.3"
echo "✅ gcloud: Google Cloud SDK..."
echo "✅ PROJECT: Set"
echo "✅ REGION: Set"
echo "✅ GCP_SA_JSON_PATH: Set"
echo "✅ WEB_ORIGINS: Set"
echo "✅ JWT_SECRET: Set"
echo "✅ All prerequisites met"
echo ""

echo "📋 STEP 3: Migration Execution"
echo "------------------------------"
echo "bash scripts/gcp_migrate.sh"
echo ""
echo "Expected output:"
echo "🔍 Starting Google Cloud Run migration..."
echo "ℹ️  Project: ai-bookkeeper-prod"
echo "ℹ️  Region: us-central1"
echo "ℹ️  Migrate Web: false"
echo "ℹ️  Cloud SQL: false"
echo "✅ All prerequisites met"
echo "✅ GCP setup complete"
echo "ℹ️  Managing secrets in Secret Manager..."
echo "✅ Secrets management complete"
echo "ℹ️  Deploying API to Cloud Run..."
echo "✅ API deployed successfully"
echo "ℹ️  API URL: https://ai-bookkeeper-api-abc123-uc.a.run.app"
echo "ℹ️  Skipping web deployment (MIGRATE_WEB=false)"
echo "ℹ️  Configuring DNS..."
echo "✅ API DNS record created: api.ai-bookkeeper.app"
echo "ℹ️  Running smoke tests..."
echo "✅ Smoke tests passed"
echo "✅ Migration completed successfully!"
echo ""

echo "📋 STEP 4: Service URLs"
echo "----------------------"
echo "API_URL=https://ai-bookkeeper-api-abc123-uc.a.run.app"
echo "WEB_URL=https://app.ai-bookkeeper.app"
echo ""

echo "📋 STEP 5: Health Check"
echo "----------------------"
echo "curl https://ai-bookkeeper-api-abc123-uc.a.run.app/healthz"
echo ""
echo "Expected response:"
echo '{"status":"ok"}'
echo ""

echo "📋 STEP 6: DNS Configuration"
echo "---------------------------"
echo "CNAME records created:"
echo "api.ai-bookkeeper.app → ai-bookkeeper-api-abc123-uc.a.run.app"
echo ""
echo "Manual DNS (if no Cloudflare token):"
echo "Create CNAME: api → ai-bookkeeper-api-abc123-uc.a.run.app"
echo ""

echo "📋 STEP 7: CORS Update"
echo "--------------------"
echo "gcloud run services update ai-bookkeeper-api \\"
echo "  --region us-central1 \\"
echo "  --set-env-vars 'ALLOWED_ORIGINS=https://app.ai-bookkeeper.app,https://ai-bookkeeper-web.onrender.com'"
echo ""

echo "📋 STEP 8: Verification"
echo "----------------------"
echo "bash scripts/smoke.sh"
echo ""
echo "Expected output:"
echo "API health OK"
echo "WEB reachable"
echo "CORS preflight OK"
echo ""

echo "📋 STEP 9: Frontend Update"
echo "-------------------------"
echo "Update your frontend (Vercel/Render) with:"
echo "NEXT_PUBLIC_API_URL=https://ai-bookkeeper-api-abc123-uc.a.run.app"
echo ""

echo "📋 STEP 10: Render Cleanup"
echo "-------------------------"
echo "After traffic is stable on Cloud Run:"
echo "1. Disable auto-deploy on Render services"
echo "2. Monitor Cloud Run metrics"
echo "3. Remove Render services when confident"
echo ""

echo "🎯 MIGRATION COMPLETE!"
echo "====================="
echo ""
echo "Your AI Bookkeeper is now running on Google Cloud Run with:"
echo "• Scalable API service with min instances"
echo "• Automatic HTTPS and global CDN"
echo "• Integrated monitoring and logging"
echo "• Secret management via Google Secret Manager"
echo "• Cost-effective pay-per-use pricing"
echo ""
echo "Next steps:"
echo "1. Complete the prerequisites setup"
echo "2. Run the actual migration"
echo "3. Test end-to-end functionality"
echo "4. Update DNS and frontend configuration"
echo "5. Monitor and optimize performance"
